# Generated by Django 4.0.4 on 2022-05-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropgrade',
            name='is_special',
            field=models.BooleanField(default=True),
        ),
    ]
