# Generated by Django 4.0.4 on 2022-05-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cropgrade_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropgrade',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
