# Generated by Django 4.0.4 on 2022-05-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cropgrade_is_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropgrade',
            name='is_special',
        ),
        migrations.AddField(
            model_name='inhousegrade',
            name='s_special',
            field=models.BooleanField(default=False),
        ),
    ]
