# Generated by Django 4.0.4 on 2022-05-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_cropgrade_is_special_inhousegrade_s_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inhousegrade',
            old_name='s_special',
            new_name='is_special',
        ),
    ]
