# Generated by Django 4.0.5 on 2023-03-20 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_s_special_inhousegrade_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='constantcode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.season'),
        ),
    ]
