# Generated by Django 4.0.4 on 2022-05-07 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('bale_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bale_weight', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductBale',
                'verbose_name_plural': 'ProductBales',
                'db_table': 'product_bale',
            },
        ),
        migrations.CreateModel(
            name='WasteBale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('reason', models.CharField(max_length=5000)),
                ('bale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_bale', to='market.bale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WasteBale',
                'verbose_name_plural': 'WasteBales',
                'db_table': 'waste_bale',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_category_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.productcategory')),
            ],
            options={
                'verbose_name': 'ProductCategory',
                'verbose_name_plural': 'ProductCategorys',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='ProductBaleInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('bale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.bale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_bale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.productbale')),
            ],
            options={
                'verbose_name': 'ProductBaleInput',
                'verbose_name_plural': 'ProductBaleInputs',
                'db_table': 'product_bale_input',
            },
        ),
        migrations.AddField(
            model_name='productbale',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='processing.productcategory'),
        ),
        migrations.AddField(
            model_name='productbale',
            name='product_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productgrade', verbose_name='product_grade'),
        ),
        migrations.CreateModel(
            name='ProcessingCentre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('centre_name', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('centre_size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Mediau'), ('LARGE', 'Large')], max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Center',
                'verbose_name_plural': 'Processing Centre',
                'db_table': 'processing_centre',
            },
        ),
    ]
