# Generated by Django 4.0.5 on 2023-03-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
