# Generated by Django 4.0.5 on 2023-03-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_user_full_name_user_phone_number_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=5000),
        ),
    ]
