# Generated by Django 4.0.4 on 2022-05-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_ticket_is_used'),
        ('inventory', '0002_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalshipment',
            name='from_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_from', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='generalshipment',
            name='is_closed_receiving',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generalshipment',
            name='is_closed_transporting',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='generalshipment',
            name='to_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_to', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='marketwarehouseshipment',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.market'),
        ),
        migrations.AlterField(
            model_name='marketwarehouseshipment',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
