# Generated by Django 4.0.4 on 2022-05-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shipment', '0002_alter_generalshipment_from_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalshipmentbale',
            name='in_house_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inhousegrade'),
        ),
    ]
