# Generated by Django 4.0.4 on 2022-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_generalshipmentbale_in_house_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalshipmentbale',
            name='testfield',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
