# Generated by Django 4.0.4 on 2022-05-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_generalshipmentbale_testfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalshipmentbale',
            name='testfield',
        ),
    ]
