# Generated by Django 4.0.4 on 2022-05-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_remove_generalshipmentbale_testfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalshipment',
            name='shipmentno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
