# Generated by Django 4.0.4 on 2022-07-01 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_rename_s_special_inhousegrade_is_special'),
        ('market', '0011_alter_bale_mn_market_alter_bale_mn_society'),
        ('shipment', '0006_generalshipment_shipmentno'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralShipmentReceivedBales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('receiving_weight', models.FloatField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('receiving_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('bale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.bale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('general_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.generalshipment')),
                ('in_house_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inhousegrade')),
                ('shipment_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cropgrade')),
            ],
            options={
                'verbose_name': 'GeneralShipmentReceivedBales',
                'verbose_name_plural': 'GeneralShipmentReceivedBales',
                'db_table': 'general_shipment_received_bales',
            },
        ),
    ]
