# Generated by Django 4.0.5 on 2023-03-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0009_generalshipmentreceivedbales_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalshipmentreceivedbales',
            name='is_sent_email',
            field=models.BooleanField(default=False),
        ),
    ]
