# Generated by Django 4.0.5 on 2023-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0010_generalshipmentreceivedbales_is_sent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalshipmentreceivedbales',
            name='is_sent_email',
        ),
        migrations.AddField(
            model_name='generalshipment',
            name='is_sent_email',
            field=models.BooleanField(default=False),
        ),
    ]
