# Generated by Django 4.0.4 on 2022-05-11 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('market', '0002_alter_ticket_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='bale',
            name='verification_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verify', to='auths.staff'),
        ),
        migrations.AddField(
            model_name='bale',
            name='verification_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
