# Generated by Django 4.0.4 on 2022-05-17 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_gradeverifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bale',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.gradeverifier'),
        ),
        migrations.AlterModelTable(
            name='gradeverifier',
            table=None,
        ),
    ]
