# Generated by Django 4.0.4 on 2022-05-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_bale_verifier_alter_gradeverifier_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bale',
            name='verifiedvalue',
            field=models.FloatField(null=True, verbose_name='verified Value'),
        ),
    ]
