# Generated by Django 4.0.4 on 2022-06-25 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_initial'),
        ('market', '0010_bale_mn_market_bale_mn_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bale',
            name='mn_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.market'),
        ),
        migrations.AlterField(
            model_name='bale',
            name='mn_society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='association.association'),
        ),
    ]
