# Generated by Django 4.0.5 on 2023-03-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_bale_mn_market_alter_bale_mn_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketticketrequest',
            name='is_mannual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printrequest',
            name='is_mannual',
            field=models.BooleanField(default=False),
        ),
    ]
