# Generated by Django 4.0.4 on 2022-05-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='is_for_sold_or_process',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
