# Generated by Django 4.0.4 on 2022-05-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_warehouse_is_for_sold_or_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='is_for_sold_or_process',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
