# Generated by Django 4.0.4 on 2022-05-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_warehouse_is_for_sold_or_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='is_for_sold_or_process',
        ),
    ]
